on:
  push:
    branches:
      ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install depenencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/Requirements.txt

      - name: Run tests
        run: pytest -v

      - name: set up docker build
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: winith039/flask-app:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Update kubeconfig and deploy
        run: |
          
          aws eks update-kubeconfig --region ap-south-1 --name autoscale-flask-eks
          
          kubectl set image deployment/flask-app flask-app=winith039/flask-app:${{ github.sha }} --record
          kubectl rollout status deployment/flask-app
