on:
  push:
    branches:
      ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install depenencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/Requirements.txt

      - name: Run tests
        run: pytest -v

      - name: set up docker build
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: winith039/flask-app:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009160066604:role/GithubActionsEKSDeployRole
          aws-region: ap-south-1
      - name: Update kubeconfig and deploy
        run: |
          
          aws eks update-kubeconfig --region ap-south-1 --name autoscale-flask-eks
          
          cat <<EOF > aws-auth.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: aws-auth
            namespace: kube-system
          data:
            mapRoles: |
              - rolearn: arn:aws:iam::009160066604:role/GithubActionsEKSDeployRole
                username: github-actions-runner
                groups:
                  - system:masters
          EOF
          kubectl apply -f aws-auth.yaml

          kubectl set image deployment/flask-webapp flask-webapp=winith039/flask-webapp:${{ github.sha }} --record
          kubectl rollout status deployment/flask-webapp
